accum_grad: 2
batch_idx: 1665
checkpoint: ../../pretrained_models/InspireMusic-1.5B-Long/llm.pt
config: conf/inspiremusic_1.5b_long.yaml
cv_data: data/BD-ESV-260106_normal_caption_dev.data.list
deepscale: false
deepscale_config: null
deepspeed: false
deepspeed_config: ./conf/ds_stage2.json
dist_backend: nccl
dtype: bf16
epoch: 7
fp16: false
freezen: true
grad_clip: 5
grad_norm: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCgAAADE1OTU3Nzk3NDRxAlgGAAAAY3VkYTowcQNLAU50cQRRLoACXXEAWAoAAAAxNTk1
    Nzc5NzQ0cQFhLgEAAAAAAAAApALKPQ==
- 0
- !!python/tuple []
- !!python/tuple []
- false
- !!python/object/apply:collections.OrderedDict
  - []
is_gradient_accumulation_boundary: false
layer_freezen: false
log_interval: 100
lora: false
lora_alpha: 16
lora_dropout: 0.1
lora_rank: 4
lora_target_modules:
- k_proj
- v_proj
loss_dict:
  acc: 0.0014987061151436397
  loss: 0.03855228669302804
lr: 2.5130308661079313e-05
max_epoch: 200
model: llm
model_dir: /root/autodl-tmp/InspireVidMuisc/InspireMusic/examples/music_generation/exp/InspireMusic-1.5b-long-BD-ESV-260106_normal_caption-s1-ft260112-1/llm/deepspeed
num_workers: 4
optim: adam
optim_conf:
  lr: 0.0001
pin_memory: true
prefetch: 8
save_per_step: 1000
save_states: model+optimizer
save_time: 13/01/2026 10:58:59
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 2000
step: 31666
tag: CV
tensorboard_dir: /root/autodl-tmp/InspireVidMuisc/InspireMusic/examples/music_generation/tensorboard/InspireMusic-1.5b-long-BD-ESV-260106_normal_caption-s1-ft260112-1/llm/deepspeed
timeout: !!python/object/apply:datetime.timedelta
- 0
- 30
- 0
train_data: data/BD-ESV-260106_normal_caption_train.data.list
train_engine: deepspeed
